name       : portaudio
version    : 20161030
release    : 6
source     :
    - http://www.portaudio.com/archives/pa_stable_v190600_20161030.tgz : f5a21d7dcd6ee84397446fa1fa1a0675bb2e8a4a6dceb4305a8404698d8d1513
license    : MIT
component  : multimedia.library
summary    : PortAudio is a free, cross-platform, open-source, audio I/O library
description: |
    PortAudio is a free, cross-platform, open-source, audio I/O library.  It lets you write simple audio programs in 'C' or C++ that will compile and run on many platforms including Windows, Macintosh OS X, and Unix (OSS/ALSA). It is intended to promote the exchange of audio software between developers on different platforms. Many applications use PortAudio for Audio I/O.
emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
setup      : |
    %configure --disable-static --enable-cxx
build      : |
    %make -j1
install    : |
    %make_install -j1
