name       : portaudio
version    : 20140130
release    : 2
source     :
    - http://www.portaudio.com/archives/pa_stable_v19_20140130.tgz : 8fe024a5f0681e112c6979808f684c3516061cc51d3acc0b726af98fc96c8d57
license    : MIT
summary    : PortAudio is a free, cross-platform, open-source, audio I/O library
description: |
    PortAudio is a free, cross-platform, open-source, audio I/O library.  It lets you write simple audio programs in 'C' or C++ that will compile and run on many platforms including Windows, Macintosh OS X, and Unix (OSS/ALSA). It is intended to promote the exchange of audio software between developers on different platforms. Many applications use PortAudio for Audio I/O.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
